language: node_js
node_js:
  - "node"
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm ci
before_script:
  - npm start -- --silent &
script:
  - npm test
  - npm run cypress:all --config videoRecording=false
before_deploy: npm install now --no-save && now --token $NOW_TOKEN rm pomodoro-app --safe --yes
deploy:
  - provider: script
    script: now --token $NOW_TOKEN --public
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: now --token $NOW_TOKEN --public && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
